# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Actualités"
  pageRef = "actualites"
  weight = 10



[[main]]
  name = "Numérique responsable"
  pageRef = "nr"
  weight = 20



[[main]]
  name = "BUT"
  pageRef = "but"
  weight = 30


[[main]]
  name = "Présentation du dîplome"
  parent = "BUT"
  pageRef = "diplome"
  weight = 10

[[main]]
  name = "Formation professionnalisante"
  parent = "BUT"
  weight = 20

[[main]]
  name = "Débouchés"
  parent = "BUT"
  weight = 30

[[main]]
  name = "Échanges universitaires"
  parent = "BUT"
  weight = 40

[[main]]
  name = "Admission"
  parent = "BUT"
  pageRef = "admission"
  weight = 50

[[main]]
  name = "Réalisations des étudiants"
  parent = "BUT"
  weight = 60

[[main]]
  name = "Que sont-ils devenus ? "
  parent = "BUT"
  weight = 70



[[main]]
  name = "Nos ressources"
  weight = 40

[[main]]
  name = "Loceaux"
  parent = "Nos ressources"
  weight = 10

[[main]]
  name = "Matériel"
  parent = "Nos ressources"
  weight = 20

[[main]]
  name = "Humain"
  parent = "Nos ressources"
  weight = 30



[[main]]
  name = "Le Puy"
  weight = 50

[[main]]
  name = "Logements / Coût de la vie"
  parent = "Le Puy"
  weight = 10

[[main]]
  name = "Activités sportives"
  parent = "Le Puy"
  weight = 20

[[main]]
  name = "Activités culturelles"
  parent = "Le Puy"
  weight = 30

[[main]]
  name = "Vie étudiante"
  parent = "Le Puy"
  weight = 40



[[footer]]
  name = "Contacts"
  pageRef ="contacts"
  weight = 10

[[footer]]
  name = "Plan du site"
  pageRef ="plan_du_site"
  weight = 20

[[footer]]
  name = "Chartes NR"
  pageRef ="charte_nr"
  weight = 30