# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Actualités"
  pageRef = "actualites"
  weight = 10

[[main]]
  name = "BUT"
  pageRef = "but_informatique_graphique"
  weight = 20

[[main]]
  name = "Présentation du dîplome"
  parent = "BUT"
  pageRef = "presentation_du_diplome"
  weight = 10

[[main]]
  name = "Débouchés"
  parent = "BUT"
  pageRef = "debouches"
  weight = 20

[[main]]
  name = "Que sont-ils devenus ? "
  parent = "BUT"
  weight = 30



[[main]]
  name = "NR"
  pageRef = "nr"
  weight = 30



[[main]]
  name = "Équipe enseignate"
  weight = 40



[[main]]
  name = "Nos ressources"
  weight = 50

[[main]]
  name = "Loceaux"
  parent = "Nos ressources"
  weight = 10

[[main]]
  name = "Matériel"
  parent = "Nos ressources"
  weight = 20

[[main]]
  name = "Humain"
  parent = "Nos ressources"
  weight = 30



[[main]]
  name = "Le Puy"
  weight = 60

[[main]]
  name = "Logements / Coût de la vie"
  parent = "Le Puy"
  weight = 10

[[main]]
  name = "Activités sportives"
  parent = "Le Puy"
  weight = 20

[[main]]
  name = "Activités culturelles"
  parent = "Le Puy"
  weight = 30

[[main]]
  name = "Vie étudiante"
  parent = "Le Puy"
  weight = 40



[[subnavigation]]
  name = "Une formation professionnalisante"
  pre = "graduation-cap"
  weight = 10

[[subnavigation]]
  name = "Échanges universitaires"
  pre = "globe"
  weight = 20

[[subnavigation]]
  name = "Modalités d'admissions"
  pre = "pencil"
  pageRef = "admission"
  weight = 30

[[subnavigation]]
  name = "Les réalisations de nos étudiants"
  pre = "code"
  weight = 40